{
    "name": "Hospital Management",
    "version": "15.0.0.0.0",
    "category": "Services",
    "summary": """Odoo module to manage the basic processes of clinic""",
    "license": "LGPL-3",
    "author": "Iva Boh",
    "maintainer": "https://github.com/IvaBoh",
    "website": "https://github.com/IvaBoh",
    "depends": [
        "base",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/hospital_disease_data.xml",
        "views/hospital_disease_views.xml",
        "views/hospital_patient_views.xml",
        "views/hospital_physician_views.xml",
        "views/hospital_visit_views.xml",
    ],
    "demo": [
        "data/hospital_patient_demo.xml",
        "data/hospital_physician_demo.xml",
    ],
    "images": ["static/description/icon.png"],
    "support": "antutilo@gmail.com",
    "application": False,
    "installable": True,
    "auto_install": False,
}
